// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvfkzoyjrjmaykjslchv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12Zmt6b3lqcmptYXlranNsY2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTg0NTMsImV4cCI6MjA2MzY5NDQ1M30.PW2B1OY1PHy182egmiwsScoemr8U9AuZrm1VUzFnNxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);